### ISSUE TITLE
Intermittent IPCExceptions kill Gfm Preview tab

### ISSUE THREAD

**Issue by dmolesUC3** [ShyykoSerhiy/gfm-plugin#107]
I'm seeing this every so often, notably when opening a project in a new window after IDEA's been running for a while. Sorry I don't have more information on underlying causes / how to reproduce -- does JXBrowser maybe have its own log somewhere that I could look at?

```
IPC process exited. Exit code: 133
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 133
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by scriptype** [comment]
I'm seeing

```
Failed to start IPC process.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/9s/jgjlbkfd7c36kwzt9j4ng_yr0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/9s/jgjlbkfd7c36kwzt9j4ng_yr0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/9s/jgjlbkfd7c36kwzt9j4ng_yr0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/9s/jgjlbkfd7c36kwzt9j4ng_yr0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
```

and this makes the plugin nonfunctional too. I keep WebStorm open for very long times and it's mostly multiple projects in separate windows.
