### ISSUE TITLE
PhpStorm 10 IDE Fatal Error after plugin install

### ISSUE THREAD

**Issue by sasha-ch** [ShyykoSerhiy/gfm-plugin#108]
![default](https://cloud.githubusercontent.com/assets/8925015/14011114/e1b979ba-f1ac-11e5-8232-67d245cf6b56.png)
Details:
```
null
java.lang.ExceptionInInitializerError
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.getDefault(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<clinit>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx.<init>(BrowserJx.java:19)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewJX.<init>(GfmPreviewJX.java:22)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewProvider.createEditor(GfmPreviewProvider.java:35)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:193)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$300(FileEditorManagerImpl.java:103)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$3$1.run(FileEditorManagerImpl.java:171)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: JxBrowser license check failed: No valid license found. 
```
![1](https://cloud.githubusercontent.com/assets/8925015/14011173/71c30ad0-f1ad-11e5-8a82-b7c9d563599f.png)

**Comment by teastburncx** [comment]
+1 in 
```
Gogland (1.0 Preview) 1.0 EAP
Build #GO-163.10615.22, built on January 9, 2017
```
