### ISSUE TITLE
Exception in thread "IPC Process Thread" java.lang.UnsatisfiedLinkError...

### ISSUE THREAD

**Issue by four43** [ShyykoSerhiy/gfm-plugin#110]
Hello,

I started having an issue with this plugin after an operating system upgrade. I used it previously on Ubuntu 14.04 and it was great.

Ubuntu 16.04:
```
~$ uname -a
Linux seth-ws 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
PHPStorm Version: 2016.1.1 (149.970)
```

```
~$ phpstorm 
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
[   3749]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
11:14:15 INFO: OS name: Linux
11:14:15 INFO: JRE version: 1.8.0_76-release 64-bit
11:14:15 INFO: JxBrowser version: 5.4.3
11:14:15 INFO: The '/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/locales' file doesn't exist.
11:14:15 INFO: Extracting Chromium binaries to '/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3'
11:14:16 INFO: The '/chromium-linux64.zip' JAR resource URL is jar:file:/home/seth/.PhpStorm2016.1/config/plugins/gfm-plugin/lib/jxbrowser-linux64-5.4.3.jar!/chromium-linux64.zip
11:14:18 INFO: Chromium binaries are extracted to '/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3'
11:14:18 INFO: Restore permissions for file: /tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser-chromium
11:14:18 INFO: Starting IPC...
11:14:18 INFO: Starting IPC Server...
11:14:18 INFO: Starting IPC Process...
11:14:18 INFO: Start Chromium process...
Exception in thread "IPC Process Thread" java.lang.UnsatisfiedLinkError: /tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Temp/libjxbrowser-common-6461f7ad-342c-41ed-9584-7597a086a8e6.so: /tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Temp/libjxbrowser-common-6461f7ad-342c-41ed-9584-7597a086a8e6.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.teamdev.jxbrowser.chromium.internal.LibraryLoader.loadLibrary(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.SharedMemoryLibrary.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.SharedMemoryLibrary.getInstance(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

I am not running another version of Java on my system, seems to be using a bundled version with PHPStorm?

This exception causes PHPStorm to hang on start for several minutes. PHPStorm seems to then kill the plugin and continue to load my project. Please let me know if there is any more information I can provide. 

Thanks for all the work on the plugin, I hope to get it running again soon. It really is great.
-Seth

**Comment by ShyykoSerhiy** [comment]
I'll have a look at this. Thx for the repport.

**Comment by ichudov** [comment]
I have the same exact problem with message ".so: failed to map segment from shared object" but using mod_perl under apache. Everything works GREAT under 14.04.

**Comment by Aivean** [comment]
Just started to have the same issue on mac:
```
Failed to start IPC process.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
```

```
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

gfm v 0.1.11
