### ISSUE TITLE
Plugin constantly crashed, reinstall helped

### ISSUE THREAD

**Issue by zuzusik** [ShyykoSerhiy/gfm-plugin#111]
Recently got issue when plugin constantly crashed until I reinstalled it. 
WebStorm showed following error details:

> Failed to start IPC process.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/bc/ty48t3956z3079ypxpzw9r6c0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/bc/ty48t3956z3079ypxpzw9r6c0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/bc/ty48t3956z3079ypxpzw9r6c0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/bc/ty48t3956z3079ypxpzw9r6c0000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more

**Comment by Aivean** [comment]
Just started to have the same issue on mac:
```
Failed to start IPC process.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/6s/8nwpgmq92tg3xwfgr7sp5fk00000gn/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
```

```
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

gfm v 0.1.11

**Comment by tagyoureit** [comment]
Seeing the same thing with the latest 2017.3 release.  Just uninstalled and reinstalled, no change.

```
Failed to start IPC process.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more


com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more


com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS/jxbrowser" (in directory "/var/folders/hk/0dkss9rd2kq5j122h4_rr__w281pb7/T/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser.app/Contents/MacOS"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more
```
