### ISSUE TITLE
Crash on opening any .md file

### ISSUE THREAD

**Issue by dotancohen** [ShyykoSerhiy/gfm-plugin#118]
Consider the following file:
```
$ cat crash_gfm.md
# Test

Hello, world!
```

Opening this file with GFM on PHPStorm 2016.3.2 EAP causes the following crash:
```
IPC process exited. Exit code: 127
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 127
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

This is running on CentOS 7.3 with KDE:
```
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 

$ uname -a
Linux TMPC013 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ kde4-config --version
Qt: 4.8.5
KDE Development Platform: 4.14.8
kde4-config: 1.0
```

**Comment by dotancohen** [comment]
Note that there are other crashers with a similar message here in the Issues, however the exit code differs.
https://github.com/ShyykoSerhiy/gfm-plugin/issues/97
https://github.com/ShyykoSerhiy/gfm-plugin/issues/107
