### ISSUE TITLE
Fatal Error when trying to close Markdown file

### ISSUE THREAD

**Issue by d4nyll** [ShyykoSerhiy/gfm-plugin#133]
When I open PyCharm Profession 2017.3 with a Markdown file already opened in the workspace, when I try to close the Markdown file, it hangs the entire IDE. In the 'IDE Fatal Errors' dialog, I get the following trace:

```
Failed to execute shutdown post message.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to execute shutdown post message.
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.stop(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.dispose(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx$4.run(BrowserJx.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
---

Initially, I thought this was a PyCharm error, and filed an issue ([#PY-28450](https://youtrack.jetbrains.com/issue/PY-28450)) at YouTrack. For more details, please refer to the ticket there.

**Comment by rask** [comment]
Same problem here. Had a `README.md` file open on my workspace which I had to keep opened to prevent PyCharm from crashing.

The following all triggered the crash:

1. Closing file tab on its own,
2. Closing the file tab with `Close other tabs` option of some other file tab,
3. Setting the tabs position to `None`.

After uninstalling this plugin the file closed normally.

**Comment by perk11** [comment]
Happens to me too in IntelliJ 2019.1 I had to disable the plugin.
