### ISSUE TITLE
v0.1.14 Crashes randomly with no md files open

### ISSUE THREAD

**Issue by alozytskyi** [ShyykoSerhiy/gfm-plugin#141]
Here's the part IDE log I've managed to recover, see last messages before shutdown.
Problem is that it happens even if I open project without any .md files, and in my understanding keeping an instance of chrome running all the time is bad idea in terms of performance.

```
11:51:46 INFO: WRITE: LoadURLMessage{type=LoadURL, uid=2, url='about:blank', frameId=-1, extraHeaders='null', postData=null}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                      [120/342]
11:51:46 INFO: [0610/115146:FATAL:scoped_file.cc(29)] Check failed: 0 == IGNORE_EINTR(close(fd)). : Bad file descriptor                                                                                               
11:51:46 INFO: [0610/115146:ERROR:renderer_main.cc(200)] Running without renderer sandbox                                                                                                                             
11:51:46 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:0,bid:0,type:Render'}, null                                                                                                             
11:51:46 INFO: Channel is accepted: SocketChannel{cid=0, bid=0, type=Render}                                                                                                                                          
11:51:46 INFO: Channel is connected: SocketChannel{cid=0, bid=0, type=Render}                                                                                                                                         
11:51:46 INFO: READ:  OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, ch
annelType=Render}                                                                                                                                                                                                     
11:51:46 INFO: WRITE: OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, ch
annelType=Render}                                                                                                                                                                                                     
11:51:46 INFO: READ:  com.teamdev.jxbrowser.chromium.internal.ipc.message.OnRenderViewCreatedMessage@d92ff78, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                               
11:51:46 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=4, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='about:blank', isErrorPage=false}, SocketInf
o{channelId=0, browserId=0, channelType=Browser}
11:51:46 INFO: READ:  OnDidCommitProvisionalLoadForFrameMessage{type=OnDidCommitProvisionalLoadForFrame, uid=5, frameId=1, isMainFrame=true, transitionType=1, url='about:blank'}, SocketInfo{channelId=0, browserId=0
, channelType=Browser}
11:51:46 INFO: READ:  OnStatusChangeMessage{type=OnStatusChangeMessage, uid=6, url=''}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                    
11:51:46 INFO: READ:  OnDocumentLoadedInFrameMessage{type=OnDocumentLoadedInFrame, uid=7, frameId=1, isMainFrame=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                    
11:51:46 INFO: READ:  OnDidFinishLoadMessage{type=OnDidFinishLoad, uid=8, frameId=1, isMainFrame=true, validatedURL='about:blank'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                        
11:51:47 INFO: [0610/115147:ERROR:browser_gpu_channel_host_factory.cc(134)] Failed to launch GPU process.
01:34:15 INFO: WRITE: PingMessage{type=Ping, uid=3, alive=false}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                                          
01:34:15 INFO: READ:  PingMessage{type=Ping, uid=3, alive=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                                           
01:34:15 INFO: WRITE: BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=4}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                       
01:34:15 INFO: READ:  BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=4}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                       
01:34:15 INFO: WRITE: DisposeBrowserMessage{type=DisposeBrowser, uid=5}, SocketInfo{channelId=0, browserId=0, channelType=Browser}                                                                                   
01:34:15 INFO: Channel is closed: SocketChannel{cid=0, bid=0, type=Browser}
01:34:15 INFO: [0610/133415:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)                                                                                  
01:34:15 INFO: Channel is disconnected: SocketChannel{cid=0, bid=0, type=Browser}
01:34:15 INFO: [0610/133415:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)                                                                         
01:34:15 INFO: Shutting down event queue...
01:34:15 INFO: Shutting down event queue... [DONE]
01:34:15 INFO: Stopping IPC...
01:34:15 INFO: Stopping main channel...
01:34:15 INFO: WRITE: ShutdownMessage{type=Shutdown, uid=6}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
01:34:15 INFO: Channel is closed: SocketChannel{cid=0, bid=0, type=Render}
01:34:15 INFO: Channel is disconnected: SocketChannel{cid=0, bid=0, type=Render}
01:34:15 INFO: Shutting down event queue...
01:34:15 INFO: Shutting down event queue... [DONE]
```

**Comment by klesun** [comment]
I have same `[0610/133415:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint` isssue on Build#IU-181.5281.24, Xubuntu 18.04.

I can reproduce it by opening two tabs: one with some `.md` file and other with some `.php` file (I guess any other will do), right-clicking on the `.php` file and pressing _Close Others_. IDEA freezes and `Stopping IPC` appears in output. Reproduces only when `gfm` plugin is enabled.
```
WARN: Python Community Edition not loaded: until build 171.SNAPSHOT < IU-181.5281.24
03:38:50 INFO: OS name: Linux
03:38:50 INFO: JRE version: 1.8.0_152-release 64-bit
03:38:50 INFO: JxBrowser version: 5.4.3
03:38:50 INFO: Starting IPC...
03:38:50 INFO: Starting IPC Server...
03:38:50 INFO: Starting IPC Process...
03:38:50 INFO: Start Chromium process...
03:38:50 INFO: The '/lib/x86_64-linux-gnu/libudev.so.0' library exists: FALSE
03:38:50 INFO: The '/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/libudev.so.0' library exists: TRUE
03:38:50 INFO: The '/lib/x86_64-linux-gnu/libgcrypt.so.11' library exists: FALSE
03:38:50 INFO: The '/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/libgcrypt.so.11' library exists: TRUE
03:38:50 INFO: Command line: /tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/jxbrowser-chromium 1101 29660 --enable-npapi 
03:38:50 INFO: [0807/153850:ERROR:browser_main_loop.cc(172)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
03:38:50 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:0,type:Main'}, null
03:38:50 INFO: Channel is accepted: SocketChannel{cid=0, bid=-1, type=Main}
03:38:50 INFO: IPC is started.
03:38:50 INFO: WRITE: CreateBrowserMessage{type=CreateBrowser, uid=0, channelId=0, contextId=-1, cacheDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Cache', memoryDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Memory', dataDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data', currentLocale='en-us', proxyType=-1, proxyRules='null', proxyBypassRules='null', proxyAutoConfigURL='null', defaultZoomLevel=0.0}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
03:38:50 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=2, message='cid:0,bid:0,type:Browser'}, null
03:38:50 INFO: Channel is accepted: SocketChannel{cid=0, bid=0, type=Browser}
03:38:50 INFO: Channel is connected: SocketChannel{cid=0, bid=0, type=Browser}
03:38:50 INFO: [0807/153850:FATAL:scoped_file.cc(29)] Check failed: 0 == IGNORE_EINTR(close(fd)). : Bad file descriptor
03:38:50 INFO: WRITE: SetNetworkDelegateConfigMessage{type=SetNetworkDelegateConfig, uid=1, browserContextId=-1, disableMessages=true}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
03:38:50 INFO: WRITE: LoadURLMessage{type=LoadURL, uid=2, url='about:blank', frameId=-1, extraHeaders='null', postData=null}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: [0807/153850:ERROR:renderer_main.cc(200)] Running without renderer sandbox
03:38:50 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:0,bid:0,type:Render'}, null
03:38:50 INFO: Channel is accepted: SocketChannel{cid=0, bid=0, type=Render}
03:38:50 INFO: Channel is connected: SocketChannel{cid=0, bid=0, type=Render}
03:38:50 INFO: READ:  OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
03:38:50 INFO: WRITE: OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=0, browserId=0, channelType=Render}
03:38:50 INFO: READ:  com.teamdev.jxbrowser.chromium.internal.ipc.message.OnRenderViewCreatedMessage@4208f0d4, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=4, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='about:blank', isErrorPage=false}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: READ:  OnDidCommitProvisionalLoadForFrameMessage{type=OnDidCommitProvisionalLoadForFrame, uid=5, frameId=1, isMainFrame=true, transitionType=1, url='about:blank'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: READ:  OnStatusChangeMessage{type=OnStatusChangeMessage, uid=6, url=''}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: READ:  OnDocumentLoadedInFrameMessage{type=OnDocumentLoadedInFrame, uid=7, frameId=1, isMainFrame=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: READ:  OnDidFinishLoadMessage{type=OnDidFinishLoad, uid=8, frameId=1, isMainFrame=true, validatedURL='about:blank'}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:50 INFO: [0807/153850:ERROR:browser_gpu_channel_host_factory.cc(134)] Failed to launch GPU process.
03:38:52 INFO: Starting IPC...
03:38:52 INFO: IPC is already started.
03:38:52 INFO: WRITE: CreateBrowserMessage{type=CreateBrowser, uid=3, channelId=1, contextId=-1, cacheDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Cache', memoryDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data/Memory', dataDir='/tmp/jxbrowser-chromium-43.0.2357.52.5.4.3/data', currentLocale='en-us', proxyType=-1, proxyRules='null', proxyBypassRules='null', proxyAutoConfigURL='null', defaultZoomLevel=0.0}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
03:38:52 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=9, message='cid:1,bid:1,type:Browser'}, null
03:38:52 INFO: Channel is accepted: SocketChannel{cid=1, bid=1, type=Browser}
03:38:52 INFO: Channel is connected: SocketChannel{cid=1, bid=1, type=Browser}
03:38:52 INFO: WRITE: SetNetworkDelegateConfigMessage{type=SetNetworkDelegateConfig, uid=4, browserContextId=-1, disableMessages=true}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
03:38:52 INFO: WRITE: LoadURLMessage{type=LoadURL, uid=5, url='about:blank', frameId=-1, extraHeaders='null', postData=null}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: [0807/153852:ERROR:renderer_main.cc(200)] Running without renderer sandbox
03:38:52 INFO: READ:  OnHelloMessage{type=OnHelloMessage, uid=1, message='cid:1,bid:1,type:Render'}, null
03:38:52 INFO: Channel is accepted: SocketChannel{cid=1, bid=1, type=Render}
03:38:52 INFO: Channel is connected: SocketChannel{cid=1, bid=1, type=Render}
03:38:52 INFO: READ:  OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=1, browserId=1, channelType=Render}
03:38:52 INFO: WRITE: OnHandleLoadMessage{type=OnHandleLoadMessage, uid=2, url='about:blank', loadType=5, loadPpolicy=2, isBackForward=false, isRedirect=false, cancel=false}, SocketInfo{channelId=1, browserId=1, channelType=Render}
03:38:52 INFO: READ:  com.teamdev.jxbrowser.chromium.internal.ipc.message.OnRenderViewCreatedMessage@58b9948b, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: READ:  OnDidStartProvisionalLoadForFrameMessage{type=OnDidStartProvisionalLoadForFrame, uid=11, frameId=1, parentFrameId=-1, isMainFrame=true, validatedURL='about:blank', isErrorPage=false}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: READ:  OnDidCommitProvisionalLoadForFrameMessage{type=OnDidCommitProvisionalLoadForFrame, uid=12, frameId=1, isMainFrame=true, transitionType=1, url='about:blank'}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: READ:  OnStatusChangeMessage{type=OnStatusChangeMessage, uid=13, url=''}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: READ:  OnDocumentLoadedInFrameMessage{type=OnDocumentLoadedInFrame, uid=14, frameId=1, isMainFrame=true}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: READ:  OnDidFinishLoadMessage{type=OnDidFinishLoad, uid=15, frameId=1, isMainFrame=true, validatedURL='about:blank'}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:52 INFO: WRITE: PingMessage{type=Ping, uid=6, alive=false}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:52 INFO: READ:  PingMessage{type=Ping, uid=6, alive=true}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:52 INFO: WRITE: BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=7}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:52 INFO: READ:  BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=7}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:52 INFO: WRITE: DisposeBrowserMessage{type=DisposeBrowser, uid=8}, SocketInfo{channelId=0, browserId=0, channelType=Browser}
03:38:52 INFO: Channel is closed: SocketChannel{cid=0, bid=0, type=Render}
03:38:52 INFO: [0807/153852:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
03:38:52 INFO: Channel is disconnected: SocketChannel{cid=0, bid=0, type=Render}
03:38:52 INFO: Channel is closed: SocketChannel{cid=0, bid=0, type=Browser}
03:38:52 INFO: Channel is disconnected: SocketChannel{cid=0, bid=0, type=Browser}
03:38:52 INFO: [0807/153852:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 2147483648, remote ID 2)
03:38:52 INFO: Shutting down event queue...
03:38:52 INFO: Shutting down event queue... [DONE]
03:38:52 INFO: Shutting down event queue...
03:38:52 INFO: Shutting down event queue...
03:38:52 INFO: Shutting down event queue... [DONE]
03:38:52 INFO: Shutting down event queue... [DONE]
03:38:54 INFO: WRITE: PingMessage{type=Ping, uid=10, alive=false}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:54 INFO: READ:  PingMessage{type=Ping, uid=10, alive=true}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:54 INFO: WRITE: BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=11}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:54 INFO: READ:  BeforeDisposeBrowserMessage{type=BeforeDisposeBrowser, uid=11}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:54 INFO: WRITE: DisposeBrowserMessage{type=DisposeBrowser, uid=12}, SocketInfo{channelId=1, browserId=1, channelType=Browser}
03:38:54 INFO: Channel is closed: SocketChannel{cid=1, bid=1, type=Browser}
03:38:54 INFO: Channel is disconnected: SocketChannel{cid=1, bid=1, type=Browser}
03:38:54 INFO: Channel is closed: SocketChannel{cid=1, bid=1, type=Render}
03:38:54 INFO: [0807/153854:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
03:38:54 INFO: Channel is disconnected: SocketChannel{cid=1, bid=1, type=Render}
03:38:54 INFO: Shutting down event queue...
03:38:54 INFO: Stopping IPC...
03:38:54 INFO: Shutting down event queue...
03:38:54 INFO: Stopping main channel...
03:38:54 INFO: Shutting down event queue... [DONE]
03:38:54 INFO: Shutting down event queue... [DONE]
03:38:54 INFO: WRITE: ShutdownMessage{type=Shutdown, uid=13}, SocketInfo{channelId=0, browserId=-1, channelType=Main}
```

**Comment by klesun** [comment]
After 5 minutes of freeze I get this stack trace:
```
Failed to execute shutdown post message.
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to execute shutdown post message.
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.stop(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.dispose(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx$4.run(BrowserJx.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
