### ISSUE TITLE
java.lang.ExceptionInInitializerError out of nowhere

### ISSUE THREAD

**Issue by bergac** [ShyykoSerhiy/gfm-plugin#150]
Out of nowhere an error occurs and IntelliJ tells me to report the issue...

OS: Mac Mojave 0.14.4 (18E226)
IntelliJ: 2019.1.1 Ultimate Edition

```
java.lang.ExceptionInInitializerError
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.getDefault(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<clinit>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx.<init>(BrowserJx.java:19)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewJX.<init>(GfmPreviewJX.java:22)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewProvider.createEditor(GfmPreviewProvider.java:35)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.java:200)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$300(FileEditorManagerImpl.java:102)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$2.lambda$exitDumbMode$0(FileEditorManagerImpl.java:162)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.teamdev.jxbrowser.chromium.internal.EnvironmentException: Unsupported Java version. Supported versions: JRE 1.6.x-1.8.x. Current version: 11.0.2
	at com.teamdev.jxbrowser.chromium.internal.Environment.checkEnvironment(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.create(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC$a.<clinit>(Unknown Source)
	... 30 more
```

**Comment by ursliurs** [comment]
Same problem here with PyCharm Community 2019.1.
