### ISSUE TITLE
IntelliJ 2019.1.2 crashes on startup with version 0.2.0

### ISSUE THREAD

**Issue by mrmanc** [ShyykoSerhiy/gfm-plugin#152]
When I upgraded IntelliJ recently I found that it was crashing a minute or so after opening any code base. I was only able to stop it doing this by deleting the gfm plugin folder. I’m running MacOS 10.14.4, Java 10.0.1 and IntelliJ 2019.1.2 Ultimate.

Here’s a message I found in my console, but I’m not sure what else to include.

```
[0517/114047.042092:FATAL:malloc_zone_functions_mac.cc(27)] Check failed: functions->malloc && functions->calloc && functions->valloc && functions->free && functions->realloc && functions->size. 
0   libbrowsercore.dylib                0x0000000192e4852c base::debug::StackTrace::StackTrace(unsigned long) + 28
1   libbrowsercore.dylib                0x0000000192daeec1 logging::LogMessage::~LogMessage() + 225
2   libbrowsercore.dylib                0x0000000192d99084 base::allocator::StoreZoneFunctions(_ChromeMallocZone const*, base::allocator::MallocZoneFunctions*) + 228
3   libbrowsercore.dylib                0x0000000192d99170 base::allocator::StoreMallocZone(_ChromeMallocZone*) + 160
4   libbrowsercore.dylib                0x0000000192d983ad base::allocator::StoreFunctionsForAllZones() + 77
5   libbrowsercore.dylib                0x0000000192e51a1d base::allocator::InitializeAllocatorShim() + 13
6   libbrowsercore.dylib                0x0000000190efce62 jxb_main + 82
7   Foundation                 <…>
```

**Comment by HenryGessau** [comment]
Crash in Pycharm 2019.1.2 when opening any markdown file:
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.getPeer()
	at com.teamdev.jxbrowser.chromium.swing.internal.NativeWin.getWindowHandle(SourceFile:37)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget$a.run(SourceFile:507)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.a(SourceFile:238)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.setVisible(SourceFile:194)
	at com.teamdev.jxbrowser.chromium.swing.BrowserView.setVisible(SourceFile:190)
	at com.intellij.openapi.project.DumbUnawareHider.setContentVisible(DumbUnawareHider.java:45)
	at com.intellij.openapi.project.DumbServiceImpl.wrapGently(DumbServiceImpl.java:417)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.createEditorComponent(EditorComposite.java:177)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.createTabbedPaneWrapper(EditorComposite.java:164)
	at com.intellij.openapi.fileEditor.impl.EditorComposite.<init>(EditorComposite.java:112)
	at com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.<init>(EditorWithProviderComposite.java:26)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.createComposite(FileEditorManagerImpl.java:990)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$8(FileEditorManagerImpl.java:878)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:672)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:768)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:699)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:145)
	at com.intellij.codeInsight.navigation.NavigationUtil.activatePsiElementIfOpen(NavigationUtil.java:200)
	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$1(NavigationUtil.java:170)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:169)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:232)
	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:116)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$null$2(AutoScrollToSourceHandler.java:170)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$scrollToSource$3(AutoScrollToSourceHandler.java:157)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ui.AutoScrollToSourceHandler.scrollToSource(AutoScrollToSourceHandler.java:157)
	at com.intellij.ui.AutoScrollToSourceHandler.lambda$onMouseClicked$0(AutoScrollToSourceHandler.java:128)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodException: com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.getPeer()
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at com.teamdev.jxbrowser.chromium.swing.internal.NativeWin.getWindowHandle(SourceFile:30)
	... 63 more
```

**Comment by Neboer** [comment]
crashs whith pycharm whith gfm 0.2.0.
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.intellij.openapi.wm.impl.IdeFrameImpl.getPeer()
	at com.teamdev.jxbrowser.chromium.swing.internal.NativeLinux.a(SourceFile:43)
	at com.teamdev.jxbrowser.chromium.swing.internal.NativeLinux.getWindowHandle(SourceFile:25)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget$a.run(SourceFile:507)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.a(SourceFile:238)
	at com.teamdev.jxbrowser.chromium.swing.internal.HeavyWeightWidget.addNotify(SourceFile:260)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Unknown Source)
	at java.desktop/javax.swing.JComponent.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Unknown Source)
	at com.intellij.ui.tabs.impl.JBTabsImpl.addImpl(JBTabsImpl.java:2654)
	at java.desktop/java.awt.Container.add(Unknown Source)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateContainer(JBTabsImpl.java:2628)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:901)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:867)
	at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:849)
	at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:96)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodException: com.intellij.openapi.wm.impl.IdeFrameImpl.getPeer()
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at com.teamdev.jxbrowser.chromium.swing.internal.NativeLinux.a(SourceFile:37)
	... 53 more
```

**Comment by ramsey** [comment]
PhpStorm 2019.1.2 is also crashing when installing this plugin. For me, it was crashing about 3-5 seconds after opening any project.

**Comment by XinHuaLuFang** [comment]
You can use the official plugin.
https://plugins.jetbrains.com/plugin/7793-markdown

**Comment by Neboer** [comment]
How to configure the official plugin's settings to make my README view just like it on the github?

**Comment by dwenzel** [comment]
I can confirm this
* gfm 0.2.0
* PhpStorm 2019.1.2, Build #PS-191.7141.52, built on May 8, 2019
* JRE: 1.8.0_202-release-1483-b49 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.14.5

Crashed during start up.

**Comment by larrywest** [comment]
I've been having this crashing problem as well - removing the ".idea" directory seemed to stop the start-up crash, but now I just re-opened GFM (0.2.0) on a README.md after deleting ".idea", and get a different symptom: 
![gfm_plugin_0 2 0_crash_after_deleting_dot_idea_subdir_Screen Shot 2019-07-01 at 2 00 23 PM](https://user-images.githubusercontent.com/8009072/60466751-684c9980-9c09-11e9-9a65-2604d6e660b6.png)

> java.lang.RuntimeException: java.lang.NoSuchMethodException: com.intellij.openapi.wm.impl.IdeFrameImpl.getPeer()
>	at com.teamdev.jxbrowser.chromium.swing.internal.NativeMac.a(SourceFile:70)
>	at com.teamdev.jxbrowser.chromium.swing.internal.NativeMac.getWindowHandle(SourceFile:34)
...
> Caused by: java.lang.NoSuchMethodException: com.intellij.openapi.wm.impl.IdeFrameImpl.getPeer()
>	at java.base/java.lang.Class.getMethod(Unknown Source)
>	at com.teamdev.jxbrowser.chromium.swing.internal.NativeMac.a(SourceFile:64)
>	... 53 more

**Comment by planetf1** [comment]
I seem to get frequent crashes with 2019.2.4 and 2019.3 EAP with gfm enabled. I've been scratching my head over constant SIGTRAPs until I came across this issue. I've uninstalled gfm for now and the problem /seems/ to have gone away. Again, using bundled JBR11

**Comment by voodoo144** [comment]
The same on 2019.2 Community Edition
