### ISSUE TITLE
Error message: Channel is already closed.

### ISSUE THREAD

**Issue by jasonszhao** [ShyykoSerhiy/gfm-plugin#44]
I constantly get this error message: 

```
Channel is already closed.
java.lang.IllegalStateException: Channel is already closed.
	at com.teamdev.jxbrowser.chromium.internal.ipc.SocketChannelWriter.write(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.SocketChannel.send(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.loadURL(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.loadURL(Unknown Source)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewJX$RequestDoneListener$1.run(GfmPreviewJX.java:68)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by ShyykoSerhiy** [comment]
Hi. Can you please provide more information about your IDE version and OS? Thanks.

**Comment by jasonszhao** [comment]
OS: Mac 10.10.2
IDE: PhpStorm 8.0.3
JRE: 1.6.0_65

**Comment by nazrhyn** [comment]
I just started using your GFM plugin today. I wasn't getting this error to start, but I've started seeing it now. If I restart WebStorm and the tab with the Markdown file is loaded automatically, it works until I close and re-open that tab. At that point, it starts throwing the errors again.

```
OS: Windows 7 64-bit
IDE: Webstorm 10.0 (32-bit)
JRE: 1.8.0_40 (32-bit)
```

**Comment by estaub** [comment]
I got this error today, in v0.1.9, but it's probably a cockpit error you may want to try to figure out how to prevent.  I'm on OSX.  For some reason (no clue, sorry!), a couple of days ago, two "JxBrowser" tabs showed up on my Dock (a.k.a. taskbar).  I puzzled a bit, did what I could to get them to tell me something about what or why they were, and quit JxBrowser, without knowing about gfm's use of it.  I suspect this caused the error today.  Restarting Intellij cleared the problem.
