### ISSUE TITLE
(Probably) causes PhpStorm 9.0 unresponding while opening a project

### ISSUE THREAD

**Issue by zpbx** [ShyykoSerhiy/gfm-plugin#71]
Love this plugin. But I encountered this issue frequently. I'm not sure if it's my fault on system config or something. Thank you for your attention.

Version: 0.1.4

Error info:

```
Failed to load 'about:blank' web page within 300 seconds.
```

Detailed “IDE Fatal Errors”:

```
Failed to load 'about:blank' web page within 300 seconds.
com.teamdev.jxbrowser.chromium.BrowserException: Failed to load 'about:blank' web page within 300 seconds.
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewJX.<init>(GfmPreviewJX.java:27)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewProvider.createEditor(GfmPreviewProvider.java:35)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:183)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$200(FileEditorManagerImpl.java:102)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$2$1.run(FileEditorManagerImpl.java:161)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:818)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:633)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:363)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:240)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:193)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:475)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:222)
	at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:56)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:61)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by ShyykoSerhiy** [comment]
Wow, that's huge. Thanks for posting. Will try to understand why it's happening and fix.
