### ISSUE TITLE
Windows 10 support(on some versions of jre)

### ISSUE THREAD

**Issue by domosapien** [ShyykoSerhiy/gfm-plugin#89]
When trying to use this plugin in windows 10, I get this error:

```
null
java.lang.ExceptionInInitializerError
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.getDefault(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.BrowserContext.<clinit>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at com.github.shyykoserhiy.gfm.browser.BrowserJx.<init>(BrowserJx.java:19)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewJX.<init>(GfmPreviewJX.java:22)
	at com.github.shyykoserhiy.gfm.editor.GfmPreviewProvider.createEditor(GfmPreviewProvider.java:35)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:183)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$200(FileEditorManagerImpl.java:102)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$2$1.run(FileEditorManagerImpl.java:161)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.teamdev.jxbrowser.chromium.internal.EnvironmentException: Unsupported operating system. Supported OS: Windows XP (SP2), 7, 8, Vista, 2003 (SP1), 2008, 2012, Mac OS X & Linux. Current OS: Windows 10
	at com.teamdev.jxbrowser.chromium.internal.Environment.checkEnvironment(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.<init>(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.create(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC$a.<clinit>(Unknown Source)
	... 28 more
```

**Comment by ShyykoSerhiy** [comment]
Can you please provide IDE version?

**Comment by domosapien** [comment]
Webstorm 10.0.4

**Comment by ShyykoSerhiy** [comment]
should be fixed in 0.1.7

**Comment by ShyykoSerhiy** [comment]
@domosapien let me know if it works now.

**Comment by domosapien** [comment]
I'll try it now, thanks!
