### ISSUE TITLE
Exception on RubyMine when opening project

### ISSUE THREAD

**Issue by pmatsinopoulos** [ShyykoSerhiy/gfm-plugin#97]
An exception occurs when I open one of my projects that uses gfm. My IDE is RubyMine.

    IPC process exited. Exit code: 133
    com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 133
	    at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	    at java.lang.Thread.run(Thread.java:745)

**Comment by ShyykoSerhiy** [comment]
Hi, please provide Os you are running  RubyMine on(and version of  RubyMine). Thx

**Comment by pmatsinopoulos** [comment]
Mac OS X Yosemite, 10.10.5
RubyMine version: 7.1.4
