### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by davidonlaptop** [ShyykoSerhiy/gfm-plugin#98]
Hey I am having difficulties installing the plugin (see image below):

![bug](http://s1.postimg.org/5jsfdem4f/Screen_Shot_2015_10_28_at_01_16_05.png)

I've created a token in GitHub with default permission scope. Which GitHub permission is required?

Also, whenever the error occurs and I go back to the plugin configuration UI, the settings are lost.

System:
* IntelliJ 14.0.3 Build IU-139.1117
* OS X 10.10 (Darwin 14.5.0)
* OpenJDK 1.8.0_45
* Scala 2.10.4

**Comment by davidonlaptop** [comment]
Even if I don't change anything and click ok I still get the error. Here's the log:

```
tail -f /Users/david/Library//Logs/IntelliJIdea14/idea.log

2015-10-28 01:24:58,824 [ 838673]  ERROR - pplication.impl.LaterInvocator - null
java.lang.NullPointerException
	at com.github.shyykoserhiy.gfm.settings.GfmGlobalSettingsConfigurable$1$1.run(GfmGlobalSettingsConfigurable.java:83)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.github.shyykoserhiy.gfm.settings.GfmGlobalSettingsConfigurable$1.run(GfmGlobalSettingsConfigurable.java:80)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-10-28 01:24:58,825 [ 838674]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 14.0.3  Build #IU-139.1117.1
2015-10-28 01:24:58,825 [ 838674]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_45
2015-10-28 01:24:58,825 [ 838674]  ERROR - pplication.impl.LaterInvocator - VM: Java HotSpot(TM) 64-Bit Server VM
2015-10-28 01:24:58,825 [ 838674]  ERROR - pplication.impl.LaterInvocator - Vendor: Oracle Corporation
2015-10-28 01:24:58,825 [ 838674]  ERROR - pplication.impl.LaterInvocator - OS: Mac OS X
```

**Comment by davidonlaptop** [comment]
Problem is fixed with latest IDEA release: 14.1.5

**Comment by ShyykoSerhiy** [comment]
BTW: What is the pros and cons of the 3 rendering engines?
You can look at 
https://github.com/ShyykoSerhiy/gfm-plugin/issues/32#issuecomment-84138220.
I would say that JXBrowser is the best option so far.

**Comment by davidonlaptop** [comment]
Great, thanks for the link!
